name: Compile and release CSS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Fetching branch
        uses: actions/checkout@v2.3.1
        with:
          ref: master

      - name: Prepare Dart
        uses: dart-lang/setup-dart@v1

      - name: Install SASS language
        run: dart pub global activate sass

      - name: Compile SASS
        run: make build

      - name: Set version variable
        run: |
          VER=$(make version)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Release build
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: false
          title: Automatic release - ${{ env.VERSION }}
          files: dist/*.css
