name: Compile and release CSS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Fetching branch
        uses: actions/checkout@v2.3.1
        with:
          ref: master

      - name: Install Dart
        uses: dart-lang/setup-dart@v1

      - name: Install SASS language
        run: pub global activate sass

      - name: Compile SASS
        run: make build

      - name: Release build
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          title: Automatic release build
          files: dist/*.css
